### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by JohnDkleadsa** [CapciGithub/Growtopia-CID-Creator-v2#3]
-bash: ./createid: Permission denied

**Comment by CapciGithub** [comment]
chmod +x createid

**Comment by JohnDkleadsa** [comment]
root@cloudshell:~$ git clone https://github.com/CapciGithub/Growtopia-CID-Creator-v2
Cloning into 'Growtopia-CID-Creator-v2'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 43 (delta 2), reused 0 (delta 0), pack-reused 38
Unpacking objects: 100% (43/43), done.
root@cloudshell:~$ cd Growtopia-CID-Creator-v2/
root@cloudshell:~/Growtopia-CID-Creator-v2$ chmod +x createid
root@cloudshell:~/Growtopia-CID-Creator-v2$ ./createid
-bash: ./createid: Permission denied
root@cloudshell:~/Growtopia-CID-Creator-v2$
