### ISSUE TITLE
stuck at connected to server

### ISSUE THREAD

**Issue by VOS21** [CapciGithub/Growtopia-CID-Creator-v2#6]
I've tried several times and used the latest port, but still stuck on connected to the server
I've been waiting for about 5 minutes but still can't

![image](https://user-images.githubusercontent.com/98244437/150662113-44114bb5-9e84-4c9d-a9d8-234ae4384d79.png)

**Comment by CapciGithub** [comment]
> I've tried several times and used the latest port, but still stuck on connected to the server I've been waiting for about 5 minutes but still can't
> 
> ![image](https://user-images.githubusercontent.com/98244437/150662113-44114bb5-9e84-4c9d-a9d8-234ae4384d79.png)

There's two reasons why it stucks there and first is: make sure there's at least 1 symbol in your password. Second is make sure the growid isnt that long and make sure you used a fake not used gmail without including @gmail.com at the end.
