### ISSUE TITLE
help

### ISSUE THREAD

**Issue by HerrAcht** [CapciGithub/Growtopia-CID-Creator-v2#7]
it always disconnecting right now after creating a few accounts, same like teohook saddd

**Comment by CapciGithub** [comment]
> it always disconnecting right now after creating a few accounts, same like teohook saddd

will check on my free time

**Comment by HerrAcht** [comment]
still busy?

**Comment by CapciGithub** [comment]
> still busy?

im not and i already have the fixed version but waiting for someone to release. If that person tells me to release i will.

**Comment by slendertaker** [comment]
> > still busy?
> 
> im not and i already have the fixed version but waiting for someone to release. If that person tells me to release i will.

When ready?

**Comment by CapciGithub** [comment]
We're still thinking about releasing it or not. If i will release you can understand probably i can change something into "fixed" on github page which will make you understand that its fixed. Also, If i release fixed version of this cid sc there might be v3 of it too.

**Comment by slendertaker** [comment]
> We're still thinking about releasing it or not. If i will release you can understand probably i can change something into "fixed" on github page which will make you understand that its fixed. Also, If i release fixed version of this cid sc there might be v3 of it too.

Ok im waiting u 👍

**Comment by CapciGithub** [comment]
released
