### ISSUE TITLE
UPDATE REQUIRED 

### ISSUE THREAD

**Issue by NafeezGG** [CapciGithub/Growtopia-CID-Creator-v2#8]
EXCUSME capci, how can i update this
`4UPDATE REQUIRED!`` : The `$V3.83`` update is now available for your device.  Go get it!  You'll need to install it before you can play online.

pls fix it.
TY

**Comment by CapciGithub** [comment]
fixed

**Comment by NafeezGG** [comment]
Error again, pls fixed
